#Config file for problem definitions
step_size: 15  #15, 30
tstep_per_day: 96
window_size: 96 #in this case is the same as tsteps_perday
num_days: 1 #days to be used somewhere
time_units: mins

#dataset
dataset_unit: kwh #kw or kwh

# data_info:
#   data_file: 'Dataset_gecad_changed.xlsx'
#   data_proc_cls: GecadDataProcessor

#Data Range
t_init: 0
t_end: 35136 # length of gecad data

#environment configs
env_info: 'training environment'
done_condition: 'mode_window'
init_condition: 'mode_window'

seed: 1024
normalization: True

#PV
pv_factor: 1


#forecasting
t_ahead_hours: 2
